version: '2'
services:
        api:
                build: .
                image: jacobcvt12/model_deployment_api
                ports:
                        - "5000:5000"
                container_name: model_deployment_api
